### ISSUE TITLE
Use cases are outside of the charter

### ISSUE THREAD

**Issue by koalie** [w3c-ccg/did-wg-charter#9] opened 2019-02-07 08:40 UTC
The mission of the WG is to enable a number of use-cases which are described in a document that lives in google docs, outside of the charter itself.

**Comment by jandrieu** [comment] 2019-02-07 08:47
Yes. I'm not sure what the issue is.

The charter specifies use cases as a deliverable, which will be a separate document from both the charter and the specification. At this stage, an early draft is in Google docs. Frankly, it's more of a gathering of input at the stage than a distilled representation of the most apt use cases. Eventually it will be a suitable description of a variety of key uses for DIDs.

That said, what are you suggesting we might do differently?

**Comment by koalie** [comment] 2019-02-07 08:52
My suggestion would be to identify a few use-cases the work enables and write those down in the "mission of the group" section instead of the pointer to google docs, or to replace the google docs link by the abstraction of what the spec fulfills.

**Comment by jandrieu** [comment] 2019-02-07 10:40
Ahh... I had forgotten that the Google link was in the charter.

I believe the intention was to get a proper ReSpec version of that document before finalizing the charter, following the example used in the Verifiable Claims Working Group charter.

We should do that.

If we did, would it address your issue? Or do you think the approach in the VCWG charter didn't work?

**Comment by sandhawke** [comment] 2019-02-09 00:44
Yeah, maybe rename the current Uses Cases document to "Some Ideas For Possible DID Use Cases", or something distancing like that.   It's quite far from a real Use Cases document.

Also, I think the charter must provide at least one solid use case.  I raised this as #10.

**Comment by koalie** [comment] 2019-02-11 10:12
@jandrieu the combination of what you suggest and what @sandhawke suggests would address my issue: identifying a few use-cases or the main one and writing that in the charter, and adding a pointer to an external document as a way to read more about that/those.

The issue is that of creating a dependency on the rationale for the working group to an external document which can be amended anytime (while the charter itself undergoes only non-substantive changes over time until substantive changes need to be made in the form of a new charter.)

**Comment by msporny** [comment] 2019-02-12 19:03
@koalie wrote:
> @jandrieu the combination of what you suggest and what @sandhawke suggests would address my issue: identifying a few use-cases or the main one and writing that in the charter, and adding a pointer to an external document as a way to read more about that/those.

The Credentials Community Group is executing on this now: https://w3c-ccg.github.io/did-use-cases/

The same group put this use cases document together for the Verifiable Credentials WG charter proposal a few years ago, so we expect it to end up in that state eventually: https://w3c.github.io/vc-use-cases/

We're behind in getting the use cases document finalized due to debate in the community regarding the level of detail necessary for the use cases... but we're on it now and will be improving the DID Use Cases document rapidly over the next week.

**Comment by nadalin** [comment] 2019-04-15 18:28
@koalie I think this would have to be a output of the WG and thus in the charter to create such a document

**Comment by koalie** [comment] 2019-04-15 22:56
@nadalin (and all) I apologise for the ambiguous title for this issue. When I raised it, the use-cases that the charter proposes the group to enable were listed outside of the charter. The issue is that the list can be updated/removed at any time. 

To fix the issue, the charter should be self-contained as much as possible.

**Comment by jandrieu** [comment] 2019-04-16 00:12
The charter explicitly includes use cases as a deliverable of the working group. As I'm sure you can appreciate, it isn't possible to put the output of the working group directly in the charter.

I recommend closing this issue as a non-issue.

**Comment by kimdhamilton** [comment] 2019-04-17 17:44
Summarizing into proposal:

- Instead of referencing the google doc, reference the more highly curated [DID use cases](https://w3c-ccg.github.io/did-use-cases/) (still in progress)
- Clarify that the use cases are not finalized inputs; rather, the WG will revisit/revise and produce use cases as outputs. I think language like this is causing the concern, and can easily be tweaked:
    - "The Credentials Community Group has developed a set of use cases and requirements that will serve as input for this document."

**Comment by nadalin** [comment] 2019-04-17 17:47
"The Credentials Community Group has developed a set of use cases and requirements that will serve as an initial input for this output document"

Also would like to make sure the IPR on this input is clean

**Comment by jandrieu** [comment] 2019-04-19 02:03
Yes. It was all developed in the CCG which has, as you know, a W3C IP policy designed to make sure it is "clean".

**Comment by jandrieu** [comment] 2019-04-19 02:04
@kimdhamilton The charter already links to the re-spec version.

**Comment by kimdhamilton** [comment] 2019-04-20 19:14
@jandrieu no argument there; the PR kept that the same

**Comment by msporny** [comment] 2019-06-27 20:15
No objections to close on DID WG Charter Task Force call on 2019-06-27. Closing.

**Closed as completed** 2019-06-27 20:15 UTC
Labels: PR merged
